### ISSUE TITLE
Uploading directories with containing files with spaces gives error.

### ISSUE THREAD

**Issue by ChrisAtkinson1** [matthewpwilson/zowe-cli#1]
I have simple structure

test2/New Text Document.txt

Running the command 

zowe zos-files upload dir-to-uss "test2" "//u//myuser//jesttest"  --zosmf-p zosms26

Error occurs.

Unexpected Command Error:
Please review the message and stack below.
Contact the creator of handler:
"C:\Users\CHRISTOPHERAtkinson\Documents\ZoweStuff\ZOWEDEV\FILE2\zowe-cli\lib\zosfiles\src\cli\upload\dtu\DirToUSSDir.handler"
Message:
Request path contains unescaped characters
Stack:
TypeError [ERR_UNESCAPED_CHARACTERS]: Request path contains unescaped characters
    at new ClientRequest (_http_client.js:115:13)
    at Object.request (https.js:281:10)
    at Promise (C:\Users\CHRISTOPHERAtkinson\Documents\ZoweStuff\ZOWEDEV\FILE2\zowe-cli\node_modules\@brightside\imperative\lib\rest\src\client\AbstractRestClient.js:82:39)
    at new Promise (<anonymous>)
    at ZosmfRestClient.performRest (C:\Users\CHRISTOPHERAtkinson\Documents\ZoweStuff\ZOWEDEV\FILE2\zowe-cli\node_modules\@brightside\imperative\lib\rest\src\client\AbstractRestClient.js:60:16)
    at Function.putExpectString (C:\Users\CHRISTOPHERAtkinson\Documents\ZoweStuff\ZOWEDEV\FILE2\zowe-cli\node_modules\@brightside\imperative\lib\rest\src\client\RestClient.js:208:34)
    at Function.<anonymous> (C:\Users\CHRISTOPHERAtkinson\Documents\ZoweStuff\ZOWEDEV\FILE2\zowe-cli\lib\zosfiles\src\api\methods\upload\Upload.js:360:43)
    at Generator.next (<anonymous>)
    at C:\Users\CHRISTOPHERAtkinson\Documents\ZoweStuff\ZOWEDEV\FILE2\zowe-cli\lib\zosfiles\src\api\methods\upload\Upload.js:17:71
    at new Promise (<anonymous>)

**Comment by matthewpwilson** [comment]
I suspect this is a base issue with directory upload.  I think I saw it mentioned  in an issue somewhere. It's possible it's been fixed in the master branch, I'm currently merging the last from there into my code so will be worth trying again after that.

**Comment by matthewpwilson** [comment]
Can you retry this with the latest code please. I can't find the fix I thought I'd spotted but I'm hoping it snuck in there :-)

**Comment by ChrisAtkinson1** [comment]
Yes I can see it working manually.  I might need to redo the test in automation.
