### ISSUE TITLE
Directories with space fail to upload.

### ISSUE THREAD

**Issue by ChrisAtkinson1** [matthewpwilson/zowe-cli#7]
If you have directory with spaces it fails with the following error.  

Files with spaces now work.

$ zowe zos-files upload dir-to-uss "dir_spacetest" "//u//atkinc//jesttest//manual" --zosmf-p zosmf26
Unexpected Command Error:
Please review the message and stack below.
Contact the creator of handler:
"C:\Users\CHRISTOPHERAtkinson\Documents\ZoweStuff\ZOWEDEV\FILE2\zowe-cli\lib\zosfiles\src\cli\upload\dtu\DirToUSSDir.handler"
Message:
Request path contains unescaped characters
Stack:
TypeError [ERR_UNESCAPED_CHARACTERS]: Request path contains unescaped characters
    at new ClientRequest (_http_client.js:115:13)
    at Object.request (https.js:281:10)
    at Promise (C:\Users\CHRISTOPHERAtkinson\Documents\ZoweStuff\ZOWEDEV\FILE2\zowe-cli\node_modules\@zowe\imperative\lib\rest\src\client\AbstractRestClient.js:82:39)
    at new Promise (<anonymous>)
    at ZosmfRestClient.performRest (C:\Users\CHRISTOPHERAtkinson\Documents\ZoweStuff\ZOWEDEV\FILE2\zowe-cli\node_modules\@zowe\imperative\lib\rest\src\client\AbstractRestClient.js:60:16)
    at Function.putExpectString (C:\Users\CHRISTOPHERAtkinson\Documents\ZoweStuff\ZOWEDEV\FILE2\zowe-cli\node_modules\@zowe\imperative\lib\rest\src\client\RestClient.js:208:34)
    at Function.<anonymous> (C:\Users\CHRISTOPHERAtkinson\Documents\ZoweStuff\ZOWEDEV\FILE2\zowe-cli\node_modules\@zowe\imperative\lib\rest\src\client\RestClient.js:66:37)
    at Generator.next (<anonymous>)
    at C:\Users\CHRISTOPHERAtkinson\Documents\ZoweStuff\ZOWEDEV\FILE2\zowe-cli\node_modules\@zowe\imperative\lib\rest\src\client\RestClient.js:17:71
    at new Promise (<anonymous>)

**Comment by matthewpwilson** [comment]
This is a base issue, suggest you raise it on the main zowe-cli repo.

**Comment by ChrisAtkinson1** [comment]
raised = https://github.com/zowe/zowe-cli/issues/314
