### ISSUE TITLE
Adding a .zosattributes file to the top level directory of the packages / system tests for upload files causes an error

### ISSUE THREAD

**Issue by ChrisAtkinson1** [matthewpwilson/zowe-cli#9]
This error occurs when adding a zosattributes file to the system test top level directory in the tests for uploading files.

$ zowe zos-files upload dir-to-uss "command_upload_dtu_dir" "//u//atkinc//jesttest//test5" --r --b --mcr 5 --zosmf-p zo
smf2c
Unexpected Command Error:
Please review the message and stack below.
Contact the creator of handler:
"C:\Users\CHRISTOPHERAtkinson\Documents\ZoweStuff\ZOWEDEV\FILE3\zowe-cli\lib\zosfiles\src\cli\upload\dtu\DirToUSSDir.handler"
Message:
Request path contains unescaped characters
Stack:
TypeError [ERR_UNESCAPED_CHARACTERS]: Request path contains unescaped characters
    at new ClientRequest (_http_client.js:115:13)
    at Object.request (https.js:281:10)
    at Promise (C:\Users\CHRISTOPHERAtkinson\Documents\ZoweStuff\ZOWEDEV\FILE3\zowe-cli\node_modules\@zowe\imperative\lib\rest\src\client\AbstractRestClient.js:82:39)
    at new Promise (<anonymous>)
    at ZosmfRestClient.performRest (C:\Users\CHRISTOPHERAtkinson\Documents\ZoweStuff\ZOWEDEV\FILE3\zowe-cli\node_modules\@zowe\imperative\lib\rest\src\client\AbstractRestClient.js:60:16)
    at Function.putExpectString (C:\Users\CHRISTOPHERAtkinson\Documents\ZoweStuff\ZOWEDEV\FILE3\zowe-cli\node_modules\@zowe\imperative\lib\rest\src\client\RestClient.js:208:34)
    at Function.<anonymous> (C:\Users\CHRISTOPHERAtkinson\Documents\ZoweStuff\ZOWEDEV\FILE3\zowe-cli\node_modules\@zowe\imperative\lib\rest\src\client\RestClient.js:66:37)
    at Generator.next (<anonymous>)
    at C:\Users\CHRISTOPHERAtkinson\Documents\ZoweStuff\ZOWEDEV\FILE3\zowe-cli\node_modules\@zowe\imperative\lib\rest\src\client\RestClient.js:17:71
    at new Promise (<anonymous>)
(node:13012) UnhandledPromiseRejectionWarning: TypeError [ERR_UNESCAPED_CHARACTERS]: Request path contains unescaped characters
    at new ClientRequest (_http_client.js:115:13)
    at Object.request (https.js:281:10)
    at Promise (C:\Users\CHRISTOPHERAtkinson\Documents\ZoweStuff\ZOWEDEV\FILE3\zowe-cli\node_modules\@zowe\imperative\lib\rest\src\client\AbstractRestClient.js:82:39)
    at new Promise (<anonymous>)
    at ZosmfRestClient.performRest (C:\Users\CHRISTOPHERAtkinson\Documents\ZoweStuff\ZOWEDEV\FILE3\zowe-cli\node_modules\@zowe\imperative\lib\rest\src\client\AbstractRestClient.js:60:16)
    at Function.putExpectString (C:\Users\CHRISTOPHERAtkinson\Documents\ZoweStuff\ZOWEDEV\FILE3\zowe-cli\node_modules\@zowe\imperative\lib\rest\src\client\RestClient.js:208:34)
    at Function.<anonymous> (C:\Users\CHRISTOPHERAtkinson\Documents\ZoweStuff\ZOWEDEV\FILE3\zowe-cli\node_modules\@zowe\imperative\lib\rest\src\client\RestClient.js:66:37)
    at Generator.next (<anonymous>)
    at C:\Users\CHRISTOPHERAtkinson\Documents\ZoweStuff\ZOWEDEV\FILE3\zowe-cli\node_modules\@zowe\imperative\lib\rest\src\client\RestClient.js:17:71
    at new Promise (<anonymous>)
(node:13012) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:13012) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by ChrisAtkinson1** [comment]
Recreation zip

[command_upload_dtu_dir.zip](https://github.com/matthewpwilson/zowe-cli/files/3064390/command_upload_dtu_dir.zip)

**Comment by ChrisAtkinson1** [comment]
example command
zowe zos-files upload dir-to-uss "command_upload_dtu_dir" "//u//atkinc//jesttest//test" --r --b --mcr 5 --zosmf-p zosmf2c

**Comment by matthewpwilson** [comment]
This should be fixed with the latest code at upload branch.

**Comment by ChrisAtkinson1** [comment]
fixed
